## rename this file before using, remove a couple of under-bar on file name.
## application.yaml__ -> application.yaml

api:
  id: 90NaqIpDfd9MKHwWpwMI
  pw: cluz_oS884

spring:
  thymeleaf:
    enable-spring-el-compiler: true
    encoding: UTF-8
    prefix: classpath:templates/ #defalut
    suffix: .html
    cache: false # only on dev
  mail:
    host:
    port:
    userName:
    password:
    #and if authentication not enable in server then remove userName and password and add this
    properties:
      mail:
        smpt:
          auth: false
          starttls:
            enable: false
