## rename this file before using, remove a couple of under-bar on file name.
## __application.yaml -> application.yaml

spring:
  thymeleaf:
    enable-spring-el-compiler: true
    encoding: UTF-8
    prefix: classpath:templates/ #defalut
    suffix: .html
    cache: false # only on dev

# get api key : https://developers.naver.com/docs/search/book/
api:
  X-Naver-Client-Id:
  X-Naver-Client-Secret:

