version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.8-rc
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=ttpbooks
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_ROOT_PASSWORD=rootpassw0rd
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql
    tty: true

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

